version: "3"
services:
  web:
    image: keineahnung2345/get-started:part1
    deploy:
      replicas: 15
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "8000:80"
    networks:
      - webnet
networks:
  webnet:
